### ISSUE TITLE
Typo with tender types (v4.0.1)

### ISSUE THREAD

**Issue by GesJeremie** [workarea-commerce/workarea-gift-cards#14]
```ruby
# config/initializers/configuration.rb
Workarea.configure do |config|
  # ...
  config.tender_types.prepend(:gift_cards)
  # ...
end
```

The slug is incorrect, I believe it should be **:gift_card** (based on the class name **Workarea::Payment::Tender::GiftCard**).

This has the major side effect to not assign a valid tender to a transaction.

Cheers 🍻

**Comment by bencrouse** [comment]
@GesJeremie can you elaborate on "major side effect to not assign a valid tender to a transaction"?

**Comment by GesJeremie** [comment]
@bencrouse While diving in production I saw those different problems:

When trying to fetch the transactions for a given payment, it wouldn't return any transactions done with a gift card.

When dumping all the **timeline events** for the given **Order** they are referenced as **"Missing Transaction"**:
![image](https://user-images.githubusercontent.com/1700610/78298060-d5b58f80-74e5-11ea-9c4f-d3b461c4cfd4.png)

After some digging it seems the reason has been commented in the code:

```ruby
# Workarea::Payment

# TODO in v4 - change this to get transactions by foreign key. Currently,
# this doesn't return all transactions for this payment if a tender failed
# validation.
def transactions
  tenders.map(&:transactions).flatten
end
```

I don't know exactly where this tender validation is failing but I saw that method in this same class:

```ruby
# Workarea::Payment
def tenders
  Workarea.config.tender_types.flat_map do |type|
    send(type)
  end.compact
end
```

It's basically doing a **send(:gift_cardS)** and can't return **Workarea::Payment::Tender::GiftCardS** (which doesn't exist).

This is where I stopped yesterday and that's why I thought **gift_cardS** was a typo ... hope it helps a bit more.

**Comment by bencrouse** [comment]
Hi @GesJeremie, I just walked through placing an order with a gift card, capturing an order with a gift card, and refunding an order with a gift card. I didn't see any problems viewing the transactions correctly.

I see there's a Netsuite integration from your screenshot, perhaps it's related to that. Otherwise please provide steps to reproduce on a vanilla Workarea app or close the issue. Thanks.

**Comment by GesJeremie** [comment]
We are still working on the issue, I'm closing the ticket for the time being :)
